---
- name: app Boxfuse provisioning
  hosts: dev
  become: yes
  
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install default-jdk and Maven
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - default-jdk
      - maven
  
  - name: GIT Clone Boxfuse
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/skawap/home_work8

  - name: maven package war
    command: mvn -f /home/skawap/home_work8/pom.xml clean package
    become: yes 
    
- name: deploy and start Boxfuse
  hosts: prod
  become: yes
 
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Install Tomcat 9
    apt:
      name: tomcat9 
      state: present

  - name: Ensure Tomcat9 is started and enabled on boot.
    service:
      name: tomcat9
      state: started 
      enabled: yes
  
  - name: Copy Remote-To-Remote (from serverA to serverB)
    synchronize: src=/home/skawap/home_work8/target/ dest=/var/lib/tomcat9/webapps/
    delegate_to: "{{ groups['dev'][0] }}"
